### ISSUE TITLE
Add more space between menu and content

### ISSUE THREAD

**Issue by christianhammar** [wolfmotherco/wm-active-admin#10]
<img width="512" alt="skarmavbild 2015-10-02 kl 16 15 43" src="https://cloud.githubusercontent.com/assets/8900421/10248611/e2a17f9a-6920-11e5-9e55-2e4b24ef0e14.png">
<img width="938" alt="skarmavbild 2015-10-02 kl 16 15 36" src="https://cloud.githubusercontent.com/assets/8900421/10248612/e2b9f11a-6920-11e5-9848-5a7d94f967e7.png">

**Comment by christianhammar** [comment]
Between menu and first row, should be 210 px-isch

**Comment by mattiasottosson** [comment]
Because missing batch actions

**Comment by christianhammar** [comment]
Updated Zeplin w new screens

**Comment by mattiasottosson** [comment]
Den här är lite bökig, placeras med javascript av active admin, så kan vi lägga den nedanför så vore det toppen

**Comment by christianhammar** [comment]
Jag gjorde en batch-knapp, såg du det?

**Comment by mattiasottosson** [comment]
Precis, den här rackarn? Grejen är att active admin togglar display block med js, så den blir svår att lägga upp en rad. =(
<img width="307" alt="screen shot 2015-10-05 at 22 32 28" src="https://cloud.githubusercontent.com/assets/616998/10292700/f9e8c680-6bb0-11e5-9a94-014abd1f439d.png">
