### ISSUE TITLE
Footer grey

### ISSUE THREAD

**Issue by christianhammar** [wolfmotherco/wm-active-admin#12]
- Link logo to wolfmother.co
- Change text style to:
  NeuzeitS-BookHeavy
  12 px
  l-s: 0.17em

**Comment by mattiasottosson** [comment]
<img width="1396" alt="screen shot 2015-10-05 at 21 07 02" src="https://cloud.githubusercontent.com/assets/616998/10290543/0b173d80-6ba5-11e5-92ff-05be9d6374e5.png">
Känns det inte lite för tjöckt?

**Comment by christianhammar** [comment]
Gör versaler :+1:
