### ISSUE TITLE
Login: Center content

### ISSUE THREAD

**Issue by christianhammar** [wolfmotherco/wm-active-admin#3]
<img width="612" alt="skarmavbild 2015-10-02 kl 15 51 47" src="https://cloud.githubusercontent.com/assets/8900421/10248096/c42d19aa-691d-11e5-9084-6c2db5a99b61.png">

**Comment by mattiasottosson** [comment]
?

**Comment by christianhammar** [comment]
Så här kanske då

<img width="680" alt="skarmavbild 2015-10-04 kl 20 19 03" src="https://cloud.githubusercontent.com/assets/8900421/10269351/336d3850-6ad5-11e5-8d36-7ce27e856b98.png">

**Comment by mattiasottosson** [comment]
Jaha, vertikalt!
