### ISSUE TITLE
Lofin: Log in btn

### ISSUE THREAD

**Issue by christianhammar** [wolfmotherco/wm-active-admin#5]
1. No pointer when rollover btn
2. Fill orange w white text when rollover

<img width="215" alt="skarmavbild 2015-10-02 kl 15 55 36" src="https://cloud.githubusercontent.com/assets/8900421/10248150/12e76974-691e-11e5-98f0-2182326f73a3.png">

**Comment by mattiasottosson** [comment]
Is button, should have pointer.

**Comment by mattiasottosson** [comment]
Ingen pointer? Antar att du menar att det ska vara en pointer? Dvs den lilla handen.

**Comment by mattiasottosson** [comment]
1b586a3d2

**Comment by christianhammar** [comment]
Ah precis
